name: SimpleGameMode
main: RianDev\SimpleGM\Main
author: RianDev
api:
- 5.0.0
description: Simple Gamemode Plugin :D
version: 0.2.0
permissions:
  gms.cmd:
    default: op
  gmc.cmd:
    default: op
  gma.cmd:
    default: op
  gmspc.cmd:
    default: op